on: [push,pull_request]
name: build and test
jobs:
  setup:
    name: install dependencies
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        
      - name: Setup flutter
        uses: takuyaohashi/setup-flutter@v1
        with:
          flutter-version: 'latest'
          channel: 'stable'

      - run: flutter doctor
      - run: flutter pub get
      - run: flutter clean
      - run: set -e # abort CI if an error happens
      - run: chmod +x ./scripts/flutter_test.sh
      - run: ./scripts/flutter_test.sh .
      - run: ./scripts/flutter_test.sh ./example
